USE DLVN;

-- 5.1. CÁC TỈNH THÀNH CÓ DIỆN TÍCH > 15000 KM2.
SELECT * 
FROM TT
WHERE DT > 15000;

-- 5.2. CÁC TỈNH THÀNH CỦA MIỀN BẮC.
SELECT *
FROM TT
WHERE MAMN = 'C01';

-- 5.3. CÁC QUỐC GIA CÓ BIÊN GIỚI VỚI CÁC TỈNH MIỀN TRUNG.
SELECT DISTINCT MAQG
FROM BG
WHERE MATT IN(
    SELECT MATT 
    FROM TT 
    WHERE MAMN = 'C02'
);

-- 5.4. MẬT ĐỘ DÂN CƯ CỦA CÁC TỈNH MIỀN TRUNG.
SELECT TENTT, DS/DT AS 'MẬT ĐỘ DÂN CƯ'
FROM TT
WHERE MAMN = 'C02';

-- 5.5. LIỆT KÊ (MÃ SỐ) CÁC TỈNH THÀNH VÙNG BIÊN GIỚI.
SELECT DISTINCT MATT
FROM LG;

-- 5.6. LIỆT KÊ (*) CÁC TỈNH THÀNH VÙNG BIÊN GIỚI VỚI CAMBODIA.
SELECT *
FROM TT
WHERE MATT IN(
    SELECT MATT
    FROM LG
    WHERE MATT IN(
        SELECT MATT
        FROM BG
        WHERE MAQG = 'CPC'
    )
);

-- 5.7. VÙNG BIÊN GIỚI CÓ BAO NHIÊU TỈNH THÀNH.
SELECT COUNT(DISTINCT MATT)
FROM BG;

-- 5.8. DIỆN TÍCH TRUNG BÌNH CỦA CÁC TỈNH MIỀN BẮC.
SELECT AVG(DT)
FROM TT
WHERE MAMN = 'C01';

-- 5.9. DIỆN TÍCH TRUNG BÌNH CỦA CÁC TỈNH THEO TỪNG MIỀN.
SELECT MAMN, AVG(DT)
FROM TT
GROUP BY MAMN;

-- 5.10. TỈNH NÀO CÓ DIỆN TÍCH LỚN NHẤT Ở MIỀN BẮC.
SELECT *
FROM TT
WHERE MAMN = 'C01'
ORDER BY DT DESC
LIMIT 1;

-- 5.11. MIỀN NÀO RỘNG LỚN NHẤT.
SELECT MAMN, SUM(DT) AS 'TỔNG DIỆN TÍCH'
FROM TT
GROUP BY MAMN
ORDER BY SUM(DT) DESC
LIMIT 1;

-- 5.12. MIỀN NÀO ĐÔNG DÂN CƯ NHẤT.
SELECT MAMN, SUM(DS) AS 'TỔNG DÂN CƯ'
FROM TT
GROUP BY MAMN
ORDER BY SUM(DS) DESC
LIMIT 1;

-- 5.13. ỨNG VỚI TỪNG MIỀN LIỆT KÊ CÁC TỈNH THÀNH CÓ DIỆN TÍCH LỚN NHẤT.
SELECT T1.MAMN, T1.TENTT, T1.DT
FROM TT T1
JOIN (
    SELECT MAMN, MAX(DT) AS MAXDT
    FROM TT
    GROUP BY MAMN
) T2 ON T1.MAMN = T2.MAMN AND T1.DT = T2.MAXDT;


-- 5.14. ỨNG VỚI TỪNG MIỀN LIỆT KÊ CÁC TỈNH THÀNH CÓ DIỆN TÍCH NHỎ NHẤT.
SELECT T1.MAMN, T1.TENTT, T1.DT
FROM TT T1
JOIN (
    SELECT MAMN, MIN(DT) AS MINDT
    FROM TT
    GROUP BY MAMN
) T2 ON T1.MAMN = T2.MAMN AND T1.DT = T2.MINDT;

-- 5.15. ỨNG VỚI TỪNG MIỀN LIỆT KÊ CÁC TỈNH THÀNH CÓ DÂN CƯ LỚN NHẤT.
SELECT T1.MAMN, T1.TENTT, T1.DS
FROM TT T1
JOIN (
    SELECT MAMN, MAX(DS) AS MAXDS
    FROM TT
    GROUP BY MAMN
) T2 ON T1.MAMN = T2.MAMN AND T1.DS = T2.MAXDS;

-- 5.16. ỨNG VỚI TỪNG MIỀN LIỆT KÊ CÁC TỈNH THÀNH CÓ DÂN CƯ NHỎ NHẤT.
SELECT T1.MAMN, T1.TENTT, T1.DS
FROM TT T1
JOIN (
    SELECT MAMN, MIN(DS) AS MINDS
    FROM TT
    GROUP BY MAMN
) T2 ON T1.MAMN = T2.MAMN AND T1.DS = T2.MINDS;

-- 5.17. CÁC TỈNH THÀNH KHÔNG PHẢI MIỀN BẮC NHƯNG LÀ LÁNG GIỀNG VỚI CÁC TỈNH MIỀN BẮC.
SELECT DISTINCT TT.*
FROM TT
WHERE MAMN != 'C01' 
AND MATT IN (
    SELECT LG.MATT
    FROM LG
    JOIN TT AS TT1 ON LG.MALG = TT1.MATT
    WHERE TT1.MAMN = 'C01'
);

-- 5.18. TỈNH THÀNH NÀO CÓ BIÊN GIỚI VỚI NHIỀU QUỐC GIA NHẤT.
SELECT TENTT
FROM TT A
JOIN BG B ON A.MATT = B.MATT
GROUP BY A.MATT, A.TENTT
HAVING COUNT(B.MAQG) = (
    SELECT MAX(SL)
    FROM (
        SELECT COUNT(MAQG) AS SL
        FROM BG
        GROUP BY MATT
    ) AS TEMP
);

-- 5.19. TỈNH THÀNH NÀO CÓ DIỆN TÍCH LỚN HƠN DIỆN TÍCH CÁC TỈNH THÀNH LÁNG GIỀNG VỚI NÓ.
SELECT T1.TENTT, T1.DT
FROM TT T1
WHERE T1.DT > ALL (
    SELECT T2.DT 
    FROM LG 
    JOIN TT T2 ON LG.MALG = T2.MATT 
    WHERE LG.MATT = T1.MATT
);

-- 5.20. TỈNH THÀNH NÀO CÓ DIỆN TÍCH LỚN HƠN DIỆN TÍCH TRUNG BÌNH CÁC TỈNH THÀNH LÁNG GIỀNG VỚI NÓ.
SELECT T1.TENTT, T1.DT
FROM TT T1
WHERE T1.DT > (
    SELECT AVG(T2.DT)
    FROM LG 
    JOIN TT T2 ON LG.MALG = T2.MATT 
    WHERE LG.MATT = T1.MATT
);