USE OMDB;

-- 5.1 ALL PRODUCTS OF CATEGORY ID = 'C02'
SELECT * 
FROM PRODUCT 
WHERE CATEGORYID = 'C02';

-- 5.2 LIST OF CUSTOMERS WHO TOOK ORDERS WITH DATE FROM D1 TO D2
SELECT DISTINCT CUSTOMERID 
FROM `ORDER` 
WHERE ORDERDATE 
BETWEEN 'D1' AND 'D2';

-- 5.3 LIST OF CUSTOMERS (ID, NAME, ADDRESS) WHO TOOK ORDERS IN YEAR 2021
SELECT DISTINCT C.CUSTOMERID, C.CUSTOMERNAME, C.CUSTOMERADDRESS 
FROM CUSTOMER C JOIN `ORDER` O ON C.CUSTOMERID = O.CUSTOMERID 
WHERE YEAR(O.ORDERDATE) = 2021;

-- 5.4 LIST OF PRODUCT IDS ORDERED IN ORDER ID = 'O01'
SELECT PRODUCTID 
FROM ORDERDETAIL 
WHERE ORDERID = 'O01';

-- 5.5 LIST OF PRODUCTS (*) ORDERED IN ORDER ID = 'O01'
SELECT P.* 
FROM PRODUCT P 
JOIN ORDERDETAIL OD ON P.PRODUCTID = OD.PRODUCTID 
WHERE OD.ORDERID = 'O01';

-- 5.6 LIST OF PRODUCTS (*) ORDERED ON ORDER DATE = D
SELECT P.* 
FROM PRODUCT P 
JOIN ORDERDETAIL OD ON P.PRODUCTID = OD.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
WHERE O.ORDERDATE = 'D';

-- 5.7 CALCULATING TOTAL QUANTITIES FOR EACH ORDER
SELECT ORDERID, SUM(ORDERQUANTITY) AS TOTALQUANTITY 
FROM ORDERDETAIL 
GROUP BY ORDERID;

-- 5.8 CALCULATING TOTAL QUANTITIES FOR EACH ORDER IN YEAR 2021
SELECT OD.ORDERID, SUM(OD.ORDERQUANTITY) AS TOTALQUANTITY 
FROM ORDERDETAIL OD JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
WHERE YEAR(O.ORDERDATE) = 2021
GROUP BY OD.ORDERID;

-- 5.9 ORDERS WITH THE LARGEST TOTAL COST
SELECT OD.ORDERID, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
GROUP BY OD.ORDERID 
ORDER BY TOTALCOST 
DESC LIMIT 1;

-- 5.10 ORDERS WITH THE LARGEST TOTAL COST IN 2021
SELECT OD.ORDERID, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
WHERE YEAR(O.ORDERDATE) = 2021 
GROUP BY OD.ORDERID 
ORDER BY TOTALCOST 
DESC LIMIT 1;

-- 5.11 CALCULATING TOTAL COST OF ORDERS FOR EACH CUSTOMER
SELECT O.CUSTOMERID, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
GROUP BY O.CUSTOMERID;

-- 5.12 CUSTOMERS WITH THE LARGEST TOTAL COST
SELECT O.CUSTOMERID, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
GROUP BY O.CUSTOMERID 
ORDER BY TOTALCOST DESC 
LIMIT 1;

SELECT A.ORDERID, SUM(UNITPRICE * ORDERQUANTITY) AS TG
FROM ORDERDETAIL A, PRODUCT B
WHERE A.PRODUCTID=B.PRODUCTID
GROUP BY `ORDERID`
HAVING TG >= ALL(
    SELECT SUM(UNITPRICE * ORDERQUANTITY)
    FROM ORDERDETAIL A, PRODUCT B
    WHERE A.PRODUCTID=B.PRODUCTID
    GROUP BY `ORDERID`
);

-- 5.13 CALCULATING TOTAL COST OF ORDERS FOR EACH CUSTOMER (ID, NAME)
SELECT C.CUSTOMERID, C.CUSTOMERNAME, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
JOIN CUSTOMER C ON O.CUSTOMERID = C.CUSTOMERID 
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME;

-- 5.14 IN 2021, CALCULATING TOTAL COST OF ORDERS FOR EACH CUSTOMER (ID, NAME)
SELECT C.CUSTOMERID, C.CUSTOMERNAME, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
JOIN CUSTOMER C ON O.CUSTOMERID = C.CUSTOMERID 
WHERE YEAR(O.ORDERDATE) = 2021 
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME;

-- 5.15 IN 2021, CUSTOMERS WITH THE LARGEST TOTAL COST
SELECT C.CUSTOMERID, C.CUSTOMERNAME, C.CUSTOMERADDRESS, SUM(OD.ORDERQUANTITY * P.UNITPRICE) AS TOTALCOST 
FROM ORDERDETAIL OD 
JOIN PRODUCT P ON OD.PRODUCTID = P.PRODUCTID 
JOIN `ORDER` O ON OD.ORDERID = O.ORDERID 
JOIN CUSTOMER C ON O.CUSTOMERID = C.CUSTOMERID 
WHERE YEAR(O.ORDERDATE) = 2021 
GROUP BY C.CUSTOMERID, C.CUSTOMERNAME, C.CUSTOMERADDRESS 
ORDER BY TOTALCOST DESC 
LIMIT 1;