USE QLDDH;

-- 5.1. CÁC KHÁCH HÀNG (MÃ SỐ) ĐẶT HÀNG TỪ NGÀY D1 ĐẾN NGÀY D2.
SELECT DISTINCT MAKH
FROM DDH
WHERE NGDH BETWEEN 'D1' AND 'D2';

-- 5.2. CÁC KHÁCH HÀNG (MÃ SỐ, TÊN VÀ ĐỊA CHỈ) ĐẶT HÀNG TRONG NĂM 2023.
SELECT A.MAKH, B.TENKH, B.DCKH
FROM DDH A, KHACH B
WHERE A.MAKH = B.MAKH AND YEAR(A.NGDH) = '2023';

-- 5.3. CÁC MẶT HÀNG (MÃ SỐ) ĐẶT TRONG ĐƠN ĐẶT HÀNG MÃ SỐ 'D01'.
SELECT DISTINCT MAHG
FROM CTDDH
WHERE MADDH = 'D01';

-- 5.4. CÁC MẶT HÀNG (*) ĐẶT TRONG ĐƠN ĐẶT HÀNG MÃ SỐ 'D01'.
SELECT *
FROM CTDDH
WHERE MADDH = 'D01';

-- 5.7. TÍNH TRỊ GIÁ CỦA TỪNG ĐƠN ĐẶT HÀNG.
SELECT DDH.MADDH, SUM(CTDDH.SLD * HANG.DG) AS TRI_GIA
FROM DDH
JOIN CTDDH ON DDH.MADDH = CTDDH.MADDH
JOIN HANG ON CTDDH.MAHG = HANG.MAHG
GROUP BY DDH.MADDH;

-- 5.8. ĐƠN ĐẶT HÀNG NÀO CÓ TRỊ GIÁ LỚN NHẤT.
SELECT CTDDH.MADDH, SUM(CTDDH.SLD * HANG.DG) AS TRI_GIA
FROM CTDDH
JOIN HANG ON CTDDH.MAHG = HANG.MAHG
GROUP BY CTDDH.MADDH
ORDER BY TRI_GIA DESC
LIMIT 1;

-- 5.9. TỔNG TRỊ GIÁ ĐẶT HÀNG CỦA TỪNG KHÁCH HÀNG (MÃ SỐ).
SELECT DDH.MAKH, SUM(SLD * DG) AS TONG_TRI_GIA
FROM CTDDH, HANG, DDH
WHERE CTDDH.MAHG = HANG.MAHG AND CTDDH.MADDH = DDH.MADDH
GROUP BY DDH.MAKH;

-- 5.10. TỔNG TRỊ GIÁ ĐẶT HÀNG CỦA TỪNG KHÁCH HÀNG (MÃ SỐ VÀ TÊN).
SELECT DDH.MAKH, TENKH, SUM(SLD * DG) AS TONG_TRI_GIA
FROM CTDDH, HANG, DDH, KHACH
WHERE CTDDH.MAHG = HANG.MAHG 
  AND CTDDH.MADDH = DDH.MADDH 
  AND DDH.MAKH = KHACH.MAKH
GROUP BY DDH.MAKH, TENKH;

-- 5.11. TỔNG TRỊ GIÁ ĐẶT HÀNG CỦA TỪNG QUÝ TRONG NĂM 2023.
SELECT QUARTER(NGDH) AS QUY, SUM(SLD * DG) AS TONG_TRI_GIA
FROM CTDDH, HANG, DDH
WHERE CTDDH.MAHG = HANG.MAHG 
  AND CTDDH.MADDH = DDH.MADDH 
  AND YEAR(NGDH) = 2023
GROUP BY QUARTER(NGDH);

-- 5.12. TRONG NĂM 2023, THÁNG NÀO CÓ TỔNG TRỊ GIÁ GIAO HÀNG LỚN NHẤT.
SELECT MONTH(NGGH) AS THANG, SUM(SLG * DG) AS TONG_TRI_GIA
FROM CTDGH, HANG, DOTGH, DDH
WHERE CTDGH.MAHG = HANG.MAHG 
  AND CTDGH.MADGH = DOTGH.MADGH 
  AND DOTGH.MADDH = DDH.MADDH
  AND YEAR(NGGH) = 2023
GROUP BY MONTH(NGGH)
ORDER BY TONG_TRI_GIA DESC
LIMIT 1;

-- 5.13. ĐƠN ĐẶT HÀNG NÀO ĐƯỢC ĐẶT TẤT CẢ CÁC MẶT HÀNG CỦA LOẠI HÀNG MÃ SỐ ”L01”.
SELECT DISTINCT MADDH
FROM CTDDH
WHERE MADDH NOT IN (
    SELECT MADDH
    FROM CTDDH, HANG
    WHERE CTDDH.MAHG = HANG.MAHG AND MALH = 'L01'
    GROUP BY MADDH
    HAVING COUNT(DISTINCT HANG.MAHG) < (
        SELECT COUNT(*)
        FROM HANG
        WHERE MALH = 'L01'
    )
);

-- 5.14. ĐƠN ĐẶT HÀNG NÀO ĐƯỢC GIAO NHIỀU ĐỢT NHẤT.
SELECT MADDH, COUNT(MADGH) AS SO_LAN_GIAO
FROM DOTGH
GROUP BY MADDH
ORDER BY SO_LAN_GIAO DESC
LIMIT 1;

-- "TÌM CÁC KHÁCH HÀNG (MAKH) ĐÃ ĐẶT TẤT CẢ CÁC MẶT HÀNG (MAHH)."
SELECT K.MAKH
FROM KHACH K
WHERE NOT EXISTS (
    SELECT H.MAHG
    FROM HANG H
    WHERE NOT EXISTS (
        SELECT CT.MAHG
        FROM CTDDH CT
        JOIN DDH D ON CT.MADDH = D.MADDH
        WHERE D.MAKH = K.MAKH AND CT.MAHG = H.MAHG
    )
);