USE QLHD;

-- TEST
SELECT MALH, COUNT(*) AS 'SOMH'
FROM HANG
GROUP BY MALH
ORDER BY MALH;

SELECT MAHD, COUNT(*) AS SLMH
FROM CTHD
GROUP BY MAHD
ORDER BY MAHD;

-- 5.1. CHO BIẾT CÁC MẶT HÀNG CỦA LOẠI HÀNG MÃ SỐ = ”LO1”.
SELECT * 
FROM HANG 
WHERE MALH = 'LO1';

-- 5.2. CHO BIẾT CÁC MẶT HÀNG (MÃ SỐ, TÊN VÀ ĐƠN GIÁ) CỦA LOẠI HÀNG MÃ SỐ ”LO2”.
SELECT MAHG, TENHG, DG 
FROM HANG 
WHERE MALH = 'LO2';

-- 5.3. CHO BIẾT CÁC MẶT HÀNG (*) CÓ ĐƠN GIÁ TỪ 100 ĐẾN 500.
SELECT * 
FROM HANG 
WHERE DG BETWEEN 100 AND 500;

-- 5.4. CHO BIẾT CÁC HÓA ĐƠN ĐƯỢC LẬP VÀO NGÀY D.
SELECT * 
FROM HOADON 
WHERE NGAYLAP = 'D';

-- 5.5. CHO BIẾT CÁC MẶT HÀNG (MÃ SỐ, TÊN, ĐƠN GIÁ VÀ SỐ LƯỢNG) CỦA NHỮNG HÓA ĐƠN LẬP VÀO NGÀY D.
SELECT H.MAHG, H.TENHG, H.DG, C.SL 
FROM HOADON HD
JOIN CTHD C ON HD.MAHD = C.MAHD
JOIN HANG H ON C.MAHG = H.MAHG
WHERE HD.NGAYLAP = '2023-07-10';

-- 5.6. CHO BIẾT CÁC HÓA ĐƠN ĐƯỢC LẬP VÀO NĂM 2023.
SELECT * 
FROM HOADON 
WHERE YEAR(NGAYLAP) = 2023;

-- 5.7. TÍNH TỔNG SỐ LƯỢNG HÀNG CỦA HÓA ĐƠN MÃ SỐ ”D01”.
SELECT SUM(SL) AS TONG_SL 
FROM CTHD 
WHERE MAHD = 'D01';

-- 5.8. TÍNH TỔNG SỐ LƯỢNG HÀNG CỦA TỪNG HÓA ĐƠN.
SELECT MAHD, SUM(SL) AS TONG_SL 
FROM CTHD 
GROUP BY MAHD;

-- 5.9. TÍNH TỔNG SỐ LƯỢNG HÀNG CỦA TỪNG HÓA ĐƠN TRONG NGÀY D.
SELECT MAHD, SUM(SL) AS TONG_SL 
FROM CTHD
WHERE MAHD IN (
    SELECT MAHD 
    FROM HOADON 
    WHERE NGAYLAP = '2023-07-10'
)
GROUP BY MAHD;

-- 5.10. TÍNH TRỊ GIÁ CỦA HÓA ĐƠN MÃ SỐ ”D01”.
SELECT SUM(A.SL * B.DG) AS TRIGIA 
FROM CTHD A, HANG B
WHERE A.MAHG = B.MAHG AND A.MAHD = 'D01';

-- 5.11. TÍNH TRỊ GIÁ CỦA TỪNG HÓA ĐƠN.
SELECT MAHD, SUM(SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG
    )
) AS TRIGIA 
FROM CTHD
GROUP BY MAHD;

-- 5.12. TRONG NGÀY D, HÓA ĐƠN NÀO CÓ TRỊ GIÁ LỚN NHẤT.
SELECT MAHD 
FROM CTHD
WHERE MAHD IN (
    SELECT MAHD 
    FROM HOADON 
    WHERE NGAYLAP = '2023-07-10'
)
GROUP BY MAHD
ORDER BY SUM(SL * (
        SELECT DG 
        FROM HANG
        WHERE HANG.MAHG = CTHD.MAHG
    )
) DESC
LIMIT 1;

-- 5.13. TÍNH TRỊ GIÁ CỦA TỪNG HÓA ĐƠN TRONG QUÍ 2 NĂM 2023.
SELECT MAHD, SUM(SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG
    )
) AS TRIGIA 
FROM CTHD
WHERE MAHD IN (
    SELECT MAHD 
    FROM HOADON 
    WHERE YEAR(NGAYLAP) = 2023 AND MONTH(NGAYLAP) BETWEEN 4 AND 6
)
GROUP BY MAHD;

-- 5.14. TÍNH TỔNG TRỊ GIÁ CỦA CÁC HÓA ĐƠN TRONG TỪNG THÁNG CỦA NĂM 2023.
SELECT MONTH(NGAYLAP) AS THANG, SUM(CTHD.SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG
    )
) AS TONGTRIGIA 
FROM HOADON, CTHD
WHERE HOADON.MAHD = CTHD.MAHD AND YEAR(HOADON.NGAYLAP) = 2023
GROUP BY MONTH(NGAYLAP);

-- 5.15. TÍNH TỔNG TRỊ GIÁ CỦA CÁC HÓA ĐƠN TRONG TỪNG QUÝ CỦA NĂM 2023.
SELECT CEIL(MONTH(NGAYLAP) / 3) AS QUY, SUM(CTHD.SL * (
        SELECT DG
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG
    )
) AS TONGTRIGIA 
FROM HOADON, CTHD
WHERE HOADON.MAHD = CTHD.MAHD AND YEAR(HOADON.NGAYLAP) = 2023
GROUP BY CEIL(MONTH(NGAYLAP) / 3);

-- 5.16. HÓA ĐƠN NÀO CÓ TRỊ GIÁ LỚN NHẤT.
SELECT MAHD 
FROM CTHD
GROUP BY MAHD
ORDER BY SUM(SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG
    )
) DESC
LIMIT 1;

-- 5.17. TRONG NĂM 2023, THÁNG NÀO CÓ TỔNG TRỊ GIÁ CÁC HÓA ĐƠN LỚN NHẤT.
SELECT THANG 
FROM (
    SELECT MONTH(NGAYLAP) AS THANG, SUM(CTHD.SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG)
        ) AS TONGTRIGIA 
    FROM HOADON, CTHD
    WHERE HOADON.MAHD = CTHD.MAHD AND YEAR(HOADON.NGAYLAP) = 2023
    GROUP BY MONTH(NGAYLAP)
) AS SUBQUERY
ORDER BY TONGTRIGIA DESC
LIMIT 1;

-- 5.18. TRONG NĂM 2023, QUÝ NÀO CÓ TỔNG TRỊ GIÁ CÁC HÓA ĐƠN LỚN NHẤT.
SELECT QUY 
FROM (
    SELECT CEIL(MONTH(NGAYLAP) / 3) AS QUY, SUM(CTHD.SL * (
        SELECT DG 
        FROM HANG 
        WHERE HANG.MAHG = CTHD.MAHG)
        ) AS TONGTRIGIA 
    FROM HOADON, CTHD
    WHERE HOADON.MAHD = CTHD.MAHD AND YEAR(HOADON.NGAYLAP) = 2023
    GROUP BY CEIL(MONTH(NGAYLAP) / 3)
) AS SUBQUERY
ORDER BY TONGTRIGIA DESC
LIMIT 1;

-- 5.19. HÓA ĐƠN NÀO CÓ TẤT CẢ CÁC MẶT HÀNG CỦA LOẠI HÀNG MÃ SỐ ”L01”.
SELECT MAHD 
FROM CTHD
WHERE MAHD NOT IN (
    SELECT DISTINCT MAHD 
    FROM CTHD 
    WHERE MAHG NOT IN (
        SELECT MAHG 
        FROM HANG 
        WHERE MALH = 'L01'
    )
)
GROUP BY MAHD;