USE QLKH;

-- 5.1. CHO BIẾT CÁC MẶT HÀNG CỦA LOẠI HÀNG MÃ SỐ 'L01'
SELECT * 
FROM HANG
WHERE MALH = 'L01';

-- 5.2. CHO BIẾT CÁC MẶT HÀNG (MÃ SỐ, TÊN VÀ ĐƠN GIÁ) CỦA LOẠI HÀNG MÃ SỐ 'L02'
SELECT MAHG, TENHG, DG 
FROM HANG 
WHERE MALH = 'L02';

-- 5.3. CHO BIẾT CÁC MẶT HÀNG CÓ ĐƠN GIÁ TỪ 100 ĐẾN 500
SELECT *
FROM HANG
WHERE DG BETWEEN 100 AND 500;

-- 5.4. CÁC KHO HÀNG ĐƯỢC PHÉP CHỨA LOẠI HÀNG MÃ SỐ 'L01'
SELECT *
FROM KH
WHERE MALH = 'L01';

-- 5.5. CÁC KHO HÀNG ĐƯỢC PHÉP CHỨA LOẠI HÀNG TÊN 'NƯỚC GIẢI KHÁT'
SELECT KH.* 
FROM KH 
JOIN LOAIHG ON KH.MALH = LOAIHG.MALH 
WHERE TENLH = 'NƯỚC GIẢI KHÁT';

-- 5.6. TẤT CẢ CÁC MẶT HÀNG CÓ THỂ CHỨA TRONG KHO MÃ SỐ 'K02'
SELECT * 
FROM HANG 
WHERE MALH = (SELECT MALH 
FROM KH 
WHERE MAKH = 'K02');

-- 5.7. TẤT CẢ CÁC MẶT HÀNG HIỆN CHỨA TRONG KHO MÃ SỐ 'K02'
SELECT HANG.* 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
WHERE MAKH = 'K02';

-- 5.8. TỔNG SỐ LƯỢNG TỒN TRONG TỪNG KHO HÀNG
SELECT MAKH, SUM(SL) AS TONG_SO_LUONG 
FROM TONKHO 
GROUP BY MAKH;

-- 5.9. KHO HÀNG CÓ TỔNG SỐ LƯỢNG TỒN LỚN NHẤT
SELECT MAKH 
FROM TONKHO 
GROUP BY MAKH 
ORDER BY SUM(SL) DESC 
LIMIT 1;

-- 5.10. SỐ LƯỢNG TỒN CỦA MẶT HÀNG MÃ SỐ 'H03'
SELECT SUM(SL) 
FROM TONKHO 
WHERE MAHG = 'H03';

-- 5.11. SỐ LƯỢNG TỒN CỦA TỪNG MẶT HÀNG CỦA LOẠI MÃ SỐ 'L01'
SELECT HANG.MAHG, SUM(SL) 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
WHERE MALH = 'L01' 
GROUP BY HANG.MAHG;

-- 5.12. SỐ LƯỢNG TỒN CỦA TỪNG MẶT HÀNG CỦA LOẠI TÊN 'NÔNG SẢN'
SELECT HANG.MAHG, SUM(SL) 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
JOIN LOAIHG ON HANG.MALH = LOAIHG.MALH 
WHERE TENLH = 'NÔNG SẢN' 
GROUP BY HANG.MAHG;

-- 5.13. SỐ LƯỢNG TỒN CỦA TỪNG MẶT HÀNG
SELECT MAHG, SUM(SL) AS TONG_SO_LUONG 
FROM TONKHO 
GROUP BY MAHG;

-- 5.14. SỐ LƯỢNG TỒN CỦA TỪNG MẶT HÀNG (MÃ SỐ VÀ TÊN)
SELECT HANG.MAHG, TENHG, SUM(SL) 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
GROUP BY HANG.MAHG, TENHG;

-- 5.15. MẶT HÀNG CÓ SỐ LƯỢNG TỒN LỚN NHẤT
SELECT MAHG 
FROM TONKHO 
GROUP BY MAHG 
ORDER BY SUM(SL) DESC 
LIMIT 1;

-- 5.16. TRỊ GIÁ CỦA KHO HÀNG MÃ SỐ 'K01'
SELECT SUM(DG * SL) 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
WHERE MAKH = 'K01';

-- 5.17. TRỊ GIÁ CỦA TỪNG KHO HÀNG
SELECT MAKH, SUM(DG * SL) AS TRI_GIA 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
GROUP BY MAKH;

-- 5.18. TRỊ GIÁ CỦA TỪNG KHO HÀNG (MÃ SỐ VÀ ĐỊA CHỈ)
SELECT KH.MAKH, DCKH, SUM(DG * SL) 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
JOIN KH ON TONKHO.MAKH = KH.MAKH 
GROUP BY KH.MAKH, DCKH;

-- 5.19. KHO HÀNG NÀO CÓ TRỊ GIÁ LỚN NHẤT
SELECT MAKH 
FROM TONKHO 
JOIN HANG ON TONKHO.MAHG = HANG.MAHG 
GROUP BY MAKH 
ORDER BY SUM(DG * SL) DESC 
LIMIT 1;

-- 5.20. KHO NÀO CHỨA ĐẦY ĐỦ CÁC MẶT HÀNG MÀ NÓ ĐƯỢC PHÉP CHỨA
SELECT MAKH 
FROM KH 
WHERE NOT EXISTS (
    SELECT * 
    FROM HANG 
    WHERE HANG.MALH = KH.MALH AND NOT EXISTS (
        SELECT * 
        FROM TONKHO 
        WHERE TONKHO.MAKH = KH.MAKH AND TONKHO.MAHG = HANG.MAHG
    )
);