USE QLSV;

-- KIỂM TRA XEM MỖI LỚP BAO NHIÊU HỌC SINH
SELECT MALP, COUNT(*) AS SISO
FROM SINHVIEN 
GROUP BY MALP
ORDER BY MALP;

-- SỐ LƯỢNG HỌC SINH
SELECT COUNT(*)
FROM `SINHVIEN`;

-- 5.1. CHO BIẾT CÁC SINH VIÊN CỦA LỚP MÃ SỐ ”L02”
SELECT *
FROM SINHVIEN
WHERE MALP = 'L01';

-- 5.2. CHO BIẾT CÁC SINH VIÊN CỦA LỚP CÓ TÊN LÀ ”COMPUTER SCIENCE” 
SELECT B.*
FROM LOP A, SINHVIEN B
WHERE A.`MALP` = B.`MALP`
AND `TENLP` = 'LỚP 1 - 2023';

-- 5.3. CHO BIẾT CÁC SINH VIÊN (ĐẦY ĐỦ THÔNG TIN) CỦA NIÊN KHÓA ”2023”
SELECT * 
FROM SINHVIEN 
WHERE MALP IN (SELECT MALP FROM LOP WHERE NK = 2023);

-- 5.4. CHO BIẾT TÊN VÀ SỐ TÍN CHỈ CỦA MÔN HỌC MÃ SỐ “M01” 
SELECT TENMH, SOTC
FROM MONHOC 
WHERE MAMH = 'M01';

-- 5.5. ĐIỂM MÔN MÃ SỐ ”M02” CỦA SINH VIÊN MÃ SỐ ”S02”
SELECT DIEM 
FROM DIEMSV 
WHERE MAMH = 'M02' AND MASV = 'S02';

-- 5.6. CHO BIẾT CÁC MÔN HỌC (MÃ SỐ, TÊN VÀ ĐIỂM) MÀ SINH VIÊN MÃ SỐ ”S02” THI RỚT
SELECT A.MAMH, TENMH, DIEM
FROM DIEMSV A, MONHOC B
WHERE DIEM < 5 AND A.MAMH = B.MAMH AND MASV = 'S02';

-- 5.8 SĨ SỐ CỦA LỚP MÃ SỐ ”L01”.
SELECT COUNT(*) 'L01'
FROM SINHVIEN
WHERE `MALP` = 'L01';

-- 5.9. SĨ SỐ TỪNG LỚP.
SELECT `MALP`, COUNT(*) SS
FROM SINHVIEN
GROUP BY MALP;

-- 5.10. LỚP CÓ SĨ SỐ LỚN NHẤT.
SELECT MALP, COUNT(*) SS
FROM SINHVIEN
GROUP BY MALP
HAVING COUNT(*) >= ALL(
    SELECT COUNT(*)
    FROM SINHVIEN
    GROUP BY MALP
);

-- 5.11. LỚP (MÃ SỐ VÀ TÊN) CÓ SĨ SỐ LỚN NHẤT.
SELECT A.MALP, B.TENLP, COUNT(*) AS SS
FROM SINHVIEN A
JOIN LOP B ON A.MALP = B.MALP
GROUP BY A.MALP, B.TENLP
HAVING COUNT(*) = (
    SELECT MAX(SS)
    FROM (
        SELECT MALP, COUNT(*) AS SS
        FROM SINHVIEN
        GROUP BY MALP
    ) AS TEMP
);

-- CÁCH KHÁC 5.11.
SELECT KQ.MALP, B.TENLP, SS
FROM (
    SELECT A.MALP, B.TENLP, COUNT(*) AS SS
    FROM SINHVIEN A
    JOIN LOP B ON A.MALP = B.MALP
    GROUP BY A.MALP, B.TENLP) AS KQ, LOP B
WHERE KQ.MALP = B.MALP;

-- 5.12. ĐIỂM TRUNG BÌNH CỦA SINH VIÊN MÃ SỐ ”S02”.
SELECT MASV, AVG(DIEM) AS DIEM_TB
FROM DIEMSV
WHERE MASV = 'S02';

-- 5.13. ĐIỂM TRUNG BÌNH CỦA TỪNG SINH VIÊN (MÃ SỐ).
SELECT MASV, AVG(DIEM) DIEM_TB
FROM DIEMSV
GROUP BY MASV;

-- 5.14. ĐIỂM TRUNG BÌNH CỦA TỪNG SINH VIÊN (MÃ SỐ VÀ TÊN).
SELECT MASV, TENSV, (
    SELECT AVG(DIEM)
    FROM DIEMSV
    WHERE MASV = SV.MASV
) DIEM_TB
FROM SINHVIEN SV;

-- 5.15. ĐIỂM TRUNG BÌNH CỦA LỚP MÃ SỐ ”L03”.
SELECT AVG(DIEM) DIEM_TB
FROM DIEMSV
WHERE MASV IN(
    SELECT MASV
    FROM SINHVIEN
    WHERE MALP = 'L03'
);

-- 5.16. ĐIỂM TRUNG BÌNH CỦA TỪNG LỚP (MÃ SỐ).
SELECT MALP, (
    SELECT AVG(DIEM)
    FROM DIEMSV
    WHERE MASV IN (
        SELECT MASV
        FROM SINHVIEN
        WHERE MALP = LOP.MALP
    )
) AS DIEM_TB
FROM LOP;

-- 5.17. ĐIỂM TRUNG BÌNH CỦA TỪNG LỚP (MÃ SỐ VÀ TÊN).
SELECT MALP, TENLP, (
    SELECT AVG(DIEM)
    FROM DIEMSV
    WHERE MASV IN (
        SELECT MASV
        FROM SINHVIEN
        WHERE MALP = LOP.MALP
    )
) AS DIEM_TB
FROM LOP;

-- 5.18. CHO BIẾT SINH VIÊN (MÃ SỐ) CÓ ĐIỂM TRUNG BÌNH LỚN NHẤT.
SELECT MASV
FROM DIEMSV
GROUP BY MASV
HAVING AVG(DIEM) = (
    SELECT MAX(DIEM_TB)
    FROM (
        SELECT AVG(DIEM) AS DIEM_TB
        FROM DIEMSV
        GROUP BY MASV
    ) AS TEMP
);

-- 5.19. CHO BIẾT SINH VIÊN (MÃ SỐ VÀ TÊN) CÓ ĐIỂM TRUNG BÌNH LỚN NHẤT.
SELECT MASV, TENSV
FROM SINHVIEN
WHERE MASV = (
    SELECT MASV
    FROM DIEMSV
    GROUP BY MASV
    HAVING AVG(DIEM) = (
        SELECT MAX(DIEM_TB)
        FROM (
            SELECT AVG(DIEM) AS DIEM_TB
            FROM DIEMSV
            GROUP BY MASV
        ) AS TEMP
    )
);

-- 5.20. ĐIỂM TRUNG BÌNH CÓ HỆ SỐ (SỐ TÍN CHỈ) CỦA TỪNG SINH VIÊN (MÃ SỐ).
SELECT MASV, SUM(DIEM * SOTC) / SUM(SOTC) AS DIEM_TB
FROM DIEMSV A, MONHOC B
WHERE A.MAMH = B.MAMH
GROUP BY MASV; 

-- 5.21. ĐIỂM TRUNG BÌNH CÓ HỆ SỐ (SỐ TÍN CHỈ) CỦA TỪNG SINH VIÊN (MÃ SỐ VÀ TÊN).
SELECT C.MASV, TENSV, SUM(DIEM * SOTC) / SUM(SOTC) AS DIEM_TB
FROM DIEMSV A, MONHOC B, SINHVIEN C
WHERE A.MAMH = B.MAMH AND A.MASV = C.MASV
GROUP BY C.MASV, C.TENSV;

-- 5.22. SINH VIÊN CÓ ĐIỂM TRUNG BÌNH CÓ HỆ SỐ LỚN NHẤT.
-- A. CHỈ CÓ MÃ SINH VIÊN
SELECT DS.MASV, SUM(DS.DIEM * MH.SOTC) / SUM(MH.SOTC) AS DIEM_TB
FROM DIEMSV DS, MONHOC MH
WHERE DS.MAMH = MH.MAMH
GROUP BY DS.MASV
HAVING DIEM_TB >= ALL(
    SELECT SUM(DIEM * SOTC) / SUM(SOTC)
    FROM DIEMSV A, MONHOC B
    WHERE A.MAMH = B.MAMH
    GROUP BY MASV
);

-- B. CÓ THÊM TÊN VÀ ĐIỂM
SELECT DS.MASV, SV.TENSV, SUM(DS.DIEM * MH.SOTC) / SUM(MH.SOTC) AS DIEM_TB
FROM DIEMSV DS, MONHOC MH, SINHVIEN SV
WHERE DS.MAMH = MH.MAMH AND DS.MASV = SV.MASV
GROUP BY DS.MASV, SV.TENSV
HAVING DIEM_TB >= ALL(
    SELECT SUM(DIEM * SOTC) / SUM(SOTC)
    FROM DIEMSV A, MONHOC B
    WHERE A.MAMH = B.MAMH
    GROUP BY MASV
);

-- CÁCH KHÁC CỦA CÂU B
SELECT TENSV, DIEM_TB
FROM SINHVIEN A, (
    SELECT DS.MASV, SUM(DS.DIEM * MH.SOTC) / SUM(MH.SOTC) AS DIEM_TB
    FROM DIEMSV DS, MONHOC MH
    WHERE DS.MAMH = MH.MAMH
    GROUP BY DS.MASV
    HAVING DIEM_TB >= ALL(
        SELECT SUM(DIEM * SOTC) / SUM(SOTC)
        FROM DIEMSV A, MONHOC B
        WHERE A.MAMH = B.MAMH
        GROUP BY MASV
    )
) AS B
WHERE A.MASV = B.MASV;

-- 5.23. ĐIỂM TRUNG BÌNH CÓ HỆ SỐ CỦA TỪNG LỚP.
-- A.
SELECT MALP, SUM(DIEM * SOTC) / SUM(SOTC) AS DTB
FROM DIEMSV A, MONHOC B, SINHVIEN C
WHERE A.MAMH = B.MAMH AND A.MASV = C.MASV
GROUP BY MALP;
-- B.
SELECT C.MALP, TENLP, SUM(DIEM * SOTC) / SUM(SOTC) AS DTB
FROM DIEMSV A, MONHOC B, SINHVIEN C, LOP D
WHERE A.MAMH = B.MAMH 
    AND A.MASV = C.MASV 
    AND C.MALP = D.MALP
GROUP BY MALP, TENLP;

-- 24. LỚP 'L01' CÓ BAO NHIÊU SINH VIEN MÔN 'M01'.
SELECT COUNT(DISTINCT DS.MASV) AS SOLUONGSINHVIEN
FROM DIEMSV DS, SINHVIEN SV
WHERE DS.MASV = SV.MASV AND SV.MALP = 'L01' AND DS.MAMH = 'M01';

-- 25. SỐ LƯỢNG SINH VIÊN RỚT CỦA TỪNG LỚP.
SELECT SV.MALP AS MALOP, COUNT(DISTINCT SV.MASV) AS SOLUONGSINHVIENROT
FROM DIEMSV DS, SINHVIEN SV
WHERE DS.MASV = SV.MAS AND DS.DIEM < 5
GROUP BY SV.MALP;

-- 26. CHO BIẾT SINH VIÊN NÀO HỌC HẾT TẤT CẢ CÁC MÔN HỌC
SELECT SV.MASV, SV.TENSV
FROM SINHVIEN SV
WHERE NOT EXISTS (
    SELECT MAMH
    FROM MONHOC
    WHERE MAMH NOT IN (
        SELECT DS.MAMH
        FROM DIEMSV DS
        WHERE DS.MASV = SV.MASV
    )
);