USE VGDB;

-- TEST
SELECT COUNT(*)
FROM PROVINCE;
--
SELECT *
FROM PROVINCE
WHERE COUNTRYID NOT IN (
	SELECT COUNTRYID
	FROM COUNTRY
);
-- 
SELECT COUNTRYID, COUNT(*)
FROM PROVINCE
GROUP BY COUNTRYID
ORDER BY COUNTRYID;
--
SELECT PROVINCEID
FROM NEIGHBOR A
GROUP BY PROVINCEID
HAVING COUNT(*) <> (
	SELECT COUNT(*)
	FROM NEIGHBOR
	WHERE A.PROVINCEID = NEIGHBORID
);
--
SELECT COUNT(*)
FROM NEIGHBOR;

-- 5.1:
SELECT *
FROM PROVINCE
WHERE AREA > 15000;
-- 5.2:
SELECT DISTINCT N.*
FROM PROVINCE P
JOIN NEIGHBOR ON P.PROVINCEID = NEIGHBOR.PROVINCEID
JOIN PROVINCE N ON NEIGHBOR.NEIGHBORID = N.PROVINCEID
WHERE P.AREA > 15
ORDER BY PROVINCEID;
-- 5.3:
SELECT A.*
FROM PROVINCE A
JOIN COUNTRY B ON A.COUNTRYID = B.COUNTRYID
WHERE B.COUNTRYNAME = 'MIEN BAC';
-- 5.4:
SELECT DISTINCT A.NATIONID
FROM BORDER A
JOIN PROVINCE B ON A.PROVINCEID = B.PROVINCEID
JOIN COUNTRY C ON C.COUNTRYID = B.COUNTRYID
WHERE C.COUNTRYID = 'C01';
-- 5.5
SELECT A.PROVINCEID, AVG(A.AREA)
FROM PROVINCE A, COUNTRY B
WHERE A.COUNTRYID = B.COUNTRYID
	AND COUNTRYNAME = 'MIEN NAM'
GROUP BY A.PROVINCEID;
-- 5.6:
SELECT SUM(A.POPULATION)/SUM(A.AREA)
FROM PROVINCE A, COUNTRY B
WHERE B.COUNTRYID = 'C02';

-- 5.6 ĐẶC BIỆT: MẬT ĐỘ DÂN SỐ CỦA CÁC TỈNH MIỀN TRUNG
SELECT PROVINCEID, PROVINCENAME, POPULATION/AREA
FROM PROVINCE
WHERE COUNTRYID = 'C02';
-- 5.7:
SELECT PROVINCEID, PROVINCENAME, POPULATION/AREA AS POPULATION_DENSITY
FROM PROVINCE
ORDER BY POPULATION_DENSITY DESC
LIMIT 1;

-- CÁCH 2:
SELECT PROVINCEID, SUM(A.POPULATION)/SUM(A.AREA) AS POPULATION_DENSITY
FROM PROVINCE A
GROUP BY PROVINCEID
HAVING SUM(A.POPULATION)/SUM(A.AREA) = (
	SELECT MAX(POPULATION_DENSITY)
	FROM (
		SELECT SUM(POPULATION)/SUM(AREA) AS POPULATION_DENSITY
		FROM PROVINCE
		GROUP BY PROVINCEID
	) AS MAXDENSITYSUBQUERY
);
-- 5.8:
-- TỈNH THÀNH(*) CÓ DIỆN TÍCH LỚN NHẤT:
SELECT *
FROM PROVINCE 
WHERE AREA = (
	SELECT MAX(AREA)
	FROM PROVINCE
);

-- TỈNH THÀNH(*) CÓ DIỆN TÍCH BÉ NHẤT:
SELECT *
FROM PROVINCE 
WHERE AREA = (
	SELECT MIN(AREA)
	FROM PROVINCE);
-- 5.9:
SELECT A.*
FROM PROVINCE A, COUNTRY B
WHERE A.COUNTRYID = B.COUNTRYID 
	AND B.COUNTRYID = 'C03'
	AND A.AREA = (
		SELECT MAX(AREA)
		FROM PROVINCE
	);
-- CÁCH KHÁC:
SELECT PROVINCEID, PROVINCENAME, POPULATION/AREA AS POPULATION_DENSITY
FROM PROVINCE
ORDER BY PROVINCEID DESC
LIMIT 1;

-- 5.10:
SELECT A.PROVINCEID, A.PROVINCENAME
FROM PROVINCE A
JOIN BORDER B ON A.PROVINCEID = B.PROVINCEID
GROUP BY A.PROVINCEID, A.PROVINCENAME
HAVING COUNT(B.NATIONID) >= 2;

-- GIỐNG CÂU 10 NHƯNG IN RA THÊM CÁC NƯỚC GIÁP
SELECT A.PROVINCEID, A.PROVINCENAME, B.NATIONID
FROM PROVINCE A
JOIN BORDER B ON A.PROVINCEID = B.PROVINCEID
WHERE A.PROVINCEID IN (
	SELECT PROVINCEID
	FROM BORDER
	GROUP BY PROVINCEID
	HAVING COUNT(*)>=2
);

-- 5.12:
SELECT A.PROVINCEID, A.PROVINCENAME, COUNT(*)
FROM PROVINCE A
JOIN NEIGHBOR B ON A.PROVINCEID = B.PROVINCEID
GROUP BY A.PROVINCEID, A.PROVINCENAME
HAVING COUNT(*) >= ALL(
	SELECT COUNT(*)
	FROM PROVINCE A
	JOIN NEIGHBOR B ON A.PROVINCEID = B.PROVINCEID
	GROUP BY A.PROVINCEID, A.PROVINCENAME
);

-- 5.13:
SELECT *
FROM PROVINCE A
WHERE AREA >= ALL (
	SELECT AREA
	FROM NEIGHBOR B, PROVINCE C
	WHERE A.PROVINCEID = B.PROVINCEID
	AND B.NEIGHBORID = C.PROVINCEID
);

-- DÂN SỐ:
SELECT *
FROM PROVINCE A
WHERE POPULATION > ALL(
	SELECT POPULATION
	FROM NEIGHBOR B, PROVINCE C
	WHERE A.PROVINCEID = B.PROVINCEID
	AND B.NEIGHBORID = C.PROVINCEID
);

-- 5.14:
SELECT *
FROM PROVINCE A
WHERE AREA > AL(
	SELECT AREA
	FROM NEIGHBOR B, PROVINCE C
	WHERE A.PROVINCEID = B.PROVINCEID
	AND B.NEIGHBORID = C.PROVINCEID
);

-- 5.15:
SELECT A.COUNTRYID, A.PROVINCEID, A.PROVINCENAME, POPULATION
FROM PROVINCE A
WHERE POPULATION > (
	SELECT AVG(POPULATION)
	FROM PROVINCE
	WHERE A.COUNTRYID = COUNTRYID
);

-- 5.16:
SELECT B.COUNTRYID, B.COUNTRYNAME, SUM(AREA)
FROM PROVINCE A, COUNTRY B
WHERE A.COUNTRYID = B.COUNTRYID
GROUP BY COUNTRYID
HAVING SUM(AREA) >= ALL(
	SELECT SUM(AREA)
	FROM PROVINCE
	GROUP BY COUNTRYID
);

-- DIỆN TÍCH MIỀN NÀO NHỎ NHẤT:

SELECT B.COUNTRYID, B.COUNTRYNAME, SUM(AREA)
FROM PROVINCE A, COUNTRY B
WHERE A.COUNTRYID = B.COUNTRYID
GROUP BY B.COUNTRYID, B.COUNTRYNAME
HAVING SUM(AREA) <= ALL(
	SELECT SUM(AREA)
	FROM PROVINCE
	GROUP BY COUNTRYID
);

-- 5.17:
SELECT B.COUNTRYID, B.COUNTRYNAME, SUM(POPULATION)
FROM PROVINCE A, COUNTRY B
WHERE A.COUNTRYID = B.COUNTRYID
GROUP BY B.COUNTRYID, B.COUNTRYNAME
HAVING SUM(POPULATION) >= ALL(
	SELECT SUM(POPULATION)
	FROM PROVINCE
	GROUP BY COUNTRYID
);